// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: protos/podinfo.proto

package podinfos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_podinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_podinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_protos_podinfo_proto_rawDescGZIP(), []int{0}
}

type PodInfoOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodName    string `protobuf:"bytes,1,opt,name=PodName,proto3" json:"PodName,omitempty"`
	WorkerName string `protobuf:"bytes,2,opt,name=WorkerName,proto3" json:"WorkerName,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *PodInfoOutput) Reset() {
	*x = PodInfoOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_podinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfoOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfoOutput) ProtoMessage() {}

func (x *PodInfoOutput) ProtoReflect() protoreflect.Message {
	mi := &file_protos_podinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfoOutput.ProtoReflect.Descriptor instead.
func (*PodInfoOutput) Descriptor() ([]byte, []int) {
	return file_protos_podinfo_proto_rawDescGZIP(), []int{1}
}

func (x *PodInfoOutput) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodInfoOutput) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *PodInfoOutput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_protos_podinfo_proto protoreflect.FileDescriptor

var file_protos_podinfo_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x64, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x63, 0x0a, 0x0d, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x6f, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x36, 0x0a, 0x07, 0x50,
	0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x6f, 0x64, 0x69, 0x6e, 0x66, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_podinfo_proto_rawDescOnce sync.Once
	file_protos_podinfo_proto_rawDescData = file_protos_podinfo_proto_rawDesc
)

func file_protos_podinfo_proto_rawDescGZIP() []byte {
	file_protos_podinfo_proto_rawDescOnce.Do(func() {
		file_protos_podinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_podinfo_proto_rawDescData)
	})
	return file_protos_podinfo_proto_rawDescData
}

var file_protos_podinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_podinfo_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil),  // 0: EmptyMessage
	(*PodInfoOutput)(nil), // 1: PodInfoOutput
}
var file_protos_podinfo_proto_depIdxs = []int32{
	0, // 0: PodInfo.GetPodInfo:input_type -> EmptyMessage
	1, // 1: PodInfo.GetPodInfo:output_type -> PodInfoOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_podinfo_proto_init() }
func file_protos_podinfo_proto_init() {
	if File_protos_podinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_podinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_podinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodInfoOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_podinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_podinfo_proto_goTypes,
		DependencyIndexes: file_protos_podinfo_proto_depIdxs,
		MessageInfos:      file_protos_podinfo_proto_msgTypes,
	}.Build()
	File_protos_podinfo_proto = out.File
	file_protos_podinfo_proto_rawDesc = nil
	file_protos_podinfo_proto_goTypes = nil
	file_protos_podinfo_proto_depIdxs = nil
}
